# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ml_service_pb2 as ml__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLServiceStub(object):
    """ML Service for PyTorch-based predictions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/noderr.ml.MLService/Predict',
                request_serializer=ml__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=ml__service__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.ClassifyRegime = channel.unary_unary(
                '/noderr.ml.MLService/ClassifyRegime',
                request_serializer=ml__service__pb2.RegimeRequest.SerializeToString,
                response_deserializer=ml__service__pb2.RegimeResponse.FromString,
                _registered_method=True)
        self.GenerateFeatures = channel.unary_unary(
                '/noderr.ml.MLService/GenerateFeatures',
                request_serializer=ml__service__pb2.FeatureRequest.SerializeToString,
                response_deserializer=ml__service__pb2.FeatureResponse.FromString,
                _registered_method=True)
        self.BatchPredict = channel.unary_unary(
                '/noderr.ml.MLService/BatchPredict',
                request_serializer=ml__service__pb2.BatchPredictRequest.SerializeToString,
                response_deserializer=ml__service__pb2.BatchPredictResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/noderr.ml.MLService/HealthCheck',
                request_serializer=ml__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ml__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class MLServiceServicer(object):
    """ML Service for PyTorch-based predictions
    """

    def Predict(self, request, context):
        """Get price predictions from Transformer ensemble
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyRegime(self, request, context):
        """Classify market regime using GAF-CNN
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateFeatures(self, request, context):
        """Generate 94-characteristic features
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchPredict(self, request, context):
        """Batch predictions for multiple symbols
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=ml__service__pb2.PredictRequest.FromString,
                    response_serializer=ml__service__pb2.PredictResponse.SerializeToString,
            ),
            'ClassifyRegime': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyRegime,
                    request_deserializer=ml__service__pb2.RegimeRequest.FromString,
                    response_serializer=ml__service__pb2.RegimeResponse.SerializeToString,
            ),
            'GenerateFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFeatures,
                    request_deserializer=ml__service__pb2.FeatureRequest.FromString,
                    response_serializer=ml__service__pb2.FeatureResponse.SerializeToString,
            ),
            'BatchPredict': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchPredict,
                    request_deserializer=ml__service__pb2.BatchPredictRequest.FromString,
                    response_serializer=ml__service__pb2.BatchPredictResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ml__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=ml__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'noderr.ml.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('noderr.ml.MLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLService(object):
    """ML Service for PyTorch-based predictions
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noderr.ml.MLService/Predict',
            ml__service__pb2.PredictRequest.SerializeToString,
            ml__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyRegime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noderr.ml.MLService/ClassifyRegime',
            ml__service__pb2.RegimeRequest.SerializeToString,
            ml__service__pb2.RegimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noderr.ml.MLService/GenerateFeatures',
            ml__service__pb2.FeatureRequest.SerializeToString,
            ml__service__pb2.FeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noderr.ml.MLService/BatchPredict',
            ml__service__pb2.BatchPredictRequest.SerializeToString,
            ml__service__pb2.BatchPredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noderr.ml.MLService/HealthCheck',
            ml__service__pb2.HealthCheckRequest.SerializeToString,
            ml__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
